const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const cfg=window.EHOOD_CONFIG||{};
const ready=cfg.SUPABASE_URL&&!cfg.SUPABASE_URL.includes('YOUR_')&&cfg.SUPABASE_ANON_KEY&&!cfg.SUPABASE_ANON_KEY.includes('YOUR_');
let supa=null,me=null,profiles=[],current='general',dmUser=null,activeGroupId='ehood';
let localMode=false;
const localAccountsKey='ehood_accounts_v6',localSessionKey='ehood_session_v6',localKey='ehood_v11_ui';
let ui=JSON.parse(localStorage.getItem(localKey)||'{}');
ui.messages=ui.messages||{};ui.groups=ui.groups||[];ui.nitro=ui.nitro||{};ui.banners=ui.banners||{};
const svg=n=>'data:image/svg+xml,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"><rect width="100%" height="100%" fill="#382146"/><text x="50%" y="58%" text-anchor="middle" font-family="Arial" font-size="44" fill="white">${(n||'?')[0].toUpperCase()}</text></svg>`);
const pic=u=>u?.avatar||svg(u?.username||'E');
const nitroActive=u=>!!u?.owner||!!ui.nitro[u?.id];
const avatarHTML=(u,cls='avatar')=>`<span class="avatar-shell"><img class="${cls}" src="${pic(u)}" alt="${esc(u?.username||'Ehood user')}">${nitroActive(u)?'<img class="nitro-pfp-badge" src="ehood-nitro-badge.png" alt="Ehood Nitro">':''}</span>`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function toast(x){const t=document.createElement('div');t.textContent=x;t.className='e-toast';document.body.appendChild(t);setTimeout(()=>t.remove(),2200)}
function modal(h){$('#modalRoot').innerHTML=`<div class="modalback" onclick="if(event.target===this)closeModal()"><div class="modal">${h}</div></div>`}
function closeModal(){$('#modalRoot').innerHTML=''} window.closeModal=closeModal;
function setMode(m){$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.mode===m));$('#usernameWrap').classList.toggle('hidden',m!=='signup');$('#authPfpWrap').classList.toggle('hidden',m!=='signup');$('#authSubmit').textContent=m==='signup'?'Create account':'Sign in';$('#authForm').dataset.mode=m;$('#authError').textContent=''}
$$('.tab').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));
function readFile(f){return new Promise(r=>{const x=new FileReader();x.onload=()=>r(x.result);x.readAsDataURL(f)})}
function getLocalAccounts(){try{return JSON.parse(localStorage.getItem(localAccountsKey)||'[]')}catch{return[]}}
function saveLocalAccounts(a){localStorage.setItem(localAccountsKey,JSON.stringify(a))}
function localUserById(id){return getLocalAccounts().find(x=>x.id===id)||null}
function saveUI(){localStorage.setItem(localKey,JSON.stringify(ui))}
function ensureLocalOwner(){const a=getLocalAccounts();if(!a.length)return;let o=a.find(x=>x.owner);if(!o){o=a[0];o.owner=true;o.verified=true;const i=a.findIndex(x=>x.id===o.id);a[i]=o;saveLocalAccounts(a)}}
function isOwner(){return !!me?.owner} function ownerGuard(){if(!isOwner()){toast('Owner only.');return false}return true}
async function boot(){
 if(ready){
  supa=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
  const {data:{session}}=await supa.auth.getSession();if(session){await loadMe(session.user.id);if(me)openApp()}
  supa.auth.onAuthStateChange(async(_e,s)=>{if(s){await loadMe(s.user.id);if(me)openApp()}else{me=null;$('#mainView').classList.add('hidden');$('#authView').classList.remove('hidden')}});
 }else{localMode=true;ensureLocalOwner();const id=localStorage.getItem(localSessionKey);if(id){me=localUserById(id);if(me&&!me.banned)openApp()}}
}
async function loadMe(id){if(localMode){ensureLocalOwner();me=localUserById(id);if(me?.banned){localStorage.removeItem(localSessionKey);me=null;$('#authError').textContent='This account is banned from Ehood.'}return}const {data,error}=await supa.from('profiles').select('*').eq('id',id).single();if(!error)me=data}
async function refreshProfiles(){if(localMode){profiles=getLocalAccounts().map(({password,...u})=>u).sort((a,b)=>a.username.localeCompare(b.username));return}const {data,error}=await supa.from('profiles').select('*').order('username');if(!error)profiles=data||[]}
function openApp(){$('#authView').classList.add('hidden');$('#mainView').classList.remove('hidden');render()}
function render(){if(!me)return;$('#selfName').textContent='@'+me.username;$('#selfAvatar').src=pic(me);$('#mobileSelfAvatar').src=pic(me);['selfAvatarWrap','mobileSelfAvatarWrap'].forEach(id=>{const w=document.getElementById(id);if(w)w.classList.toggle('has-nitro',nitroActive(me))});renderServers();renderChannels();renderMembers();select(current)}
function renderServers(){const el=$('#servers');if(!el)return;el.innerHTML=ui.groups.map(g=>`<button class="server group-server ${g.id===activeGroupId?'active':''}" title="${esc(g.name)}" onclick="selectGroup('${g.id}')">${esc(g.icon||g.name[0]||'G')}</button>`).join('')}
function selectGroup(id){activeGroupId=id;dmUser=null;current='general';renderServers();renderChannels();select('general')}
window.selectGroup=selectGroup;
function groupById(id){return ui.groups.find(g=>g.id===id)}
function currentGroup(){return activeGroupId==='ehood'?{id:'ehood',name:'Ehood',icon:'E'}:groupById(activeGroupId)||{id:'ehood',name:'Ehood',icon:'E'}}
function renderChannels(){const names=['general','chat'];const g=currentGroup();const del=g.id!=='ehood'?`<button class="channel group-delete" onclick="deleteGroup('${g.id}')">🗑️ Delete Group</button>`:'';$('#channels').innerHTML=names.map(n=>`<button class="channel ${n===current&&!dmUser?'active':''}" data-ch="${n}"># ${n}</button>`).join('')+`<button class="channel voice-channel" onclick="joinVoice('${g.id}','General')">🔊 General <span>VOICE</span></button>${del}`;$$('[data-ch]').forEach(b=>b.onclick=()=>{dmUser=null;select(b.dataset.ch)})}
function localMessages(key){ui.messages[key]=ui.messages[key]||[];return ui.messages[key]}
function channelKey(){return `${activeGroupId}:${dmUser?'dm_'+[me.id,dmUser.id].sort().join('_'):current}`}
function select(n){current=n;$('#chatTitle').textContent=n;const g=currentGroup();$('#topic').textContent=dmUser?'Direct message':`${g.name} · ${n==='general'?'Welcome to Ehood.':'Talk about whatever you want.'}`;$('#messageInput').placeholder=dmUser?'Message @'+dmUser.username:'Message #'+n;renderChannels();renderMessages()}
function renderMessages(){const arr=localMessages(channelKey());$('#messages').innerHTML=arr.map((m,i)=>{const u=profiles.find(x=>x.id===m.user_id)||me;const can=m.user_id===me.id||isOwner();return `<div class="msg">${avatarHTML(u)}<div class="msgbody"><div class="meta"><b>${esc(u.username)}</b>${u.verified?'<span class="verified">✓</span>':''}<time>${new Date(m.time).toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}${m.edited?' <span class="edited">(edited)</span>':''}</time></div>${m.text?`<div class="text">${esc(m.text)}</div>`:''}${m.image?`<img class="message-image" src="${m.image}" alt="${esc(m.imageName||'Image')}" onclick="window.open(this.src,'_blank')">`:''}${can?`<div class="msg-actions"><button class="msg-action" onclick="editMessage(${i})">Edit</button><button class="msg-action danger" onclick="deleteMessage(${i})">Delete</button></div>`:''}</div></div>`}).join('');$('#messages').scrollTop=1e9}
function editMessage(i){const a=localMessages(channelKey()),m=a[i];if(!m)return;if(m.user_id!==me.id&&!isOwner())return toast('You can only edit your own messages.');const n=prompt('Edit message:',m.text);if(n===null)return;const t=n.trim();if(!t)return toast('Message cannot be empty.');m.text=t;m.edited=true;saveUI();renderMessages()}
function deleteGroup(id){const g=groupById(id);if(!g)return;if(g.owner_id!==me.id&&!isOwner())return toast('Only the group owner or Ehood owner can delete this group.');if(!confirm(`Delete ${g.name}?`))return;ui.groups=ui.groups.filter(x=>x.id!==id);Object.keys(ui.messages).forEach(k=>{if(k.startsWith(id+':'))delete ui.messages[k]});activeGroupId='ehood';current='general';saveUI();render();toast('Group deleted.')}
window.deleteGroup=deleteGroup;
function deleteMessage(i){const g=groupById(id);if(!g)return;if(g.owner_id!==me.id&&!isOwner())return toast('Only the group owner or Ehood owner can delete this group.');if(!confirm(`Delete ${g.name}?`))return;ui.groups=ui.groups.filter(x=>x.id!==id);Object.keys(ui.messages).forEach(k=>{if(k.startsWith(id+':'))delete ui.messages[k]});activeGroupId='ehood';current='general';saveUI();render();toast('Group deleted.')}
window.deleteGroup=deleteGroup;
function deleteMessage(i){const a=localMessages(channelKey()),m=a[i];if(!m)return;if(m.user_id!==me.id&&!isOwner())return toast('You can only delete your own messages.');if(!confirm('Delete this message?'))return;a.splice(i,1);saveUI();renderMessages()}
window.editMessage=editMessage;window.deleteMessage=deleteMessage;
function dm(id){const u=profiles.find(x=>x.id===id);if(!u)return;dmUser=u;select('dm')}
window.dm=dm;
async function sendMessage(){if(me?.banned)return toast('You are banned from Ehood.');if(me?.muted)return toast('You are muted.');const t=$('#messageInput').value.trim();const f=$('#imageInput')?.files?.[0];if(!t&&!f)return;const m={user_id:me.id,text:t,time:Date.now()};if(f){if(!f.type.startsWith('image/'))return toast('Please choose an image.');m.image=await readFile(f);m.imageName=f.name}localMessages(channelKey()).push(m);saveUI();$('#messageInput').value='';if($('#imageInput'))$('#imageInput').value='';renderMessages()}
$('#composer').onsubmit=e=>{e.preventDefault();sendMessage()};
async function renderMembers(){await refreshProfiles();$('#memberList').innerHTML=profiles.map(u=>`<div class="member" onclick="profileModal('${u.id}')">${avatarHTML(u)}<span><b>@${esc(u.username)} ${u.verified?'<span class="verified">✓</span>':''}</b><small>${u.id===me.id?'● Online':'● Online · Click to view'}</small></span></div>`).join('')}
function nitroInfo(){const active=!!ui.nitro[me.id];modal(`<div class="nitro-page"><div class="nitro-icon">✨</div><h2>Ehood Nitro</h2><p class="muted">Premium customization for your Ehood profile.</p><div class="nitro-price">$2.99 <span>/ month</span></div><div class="nitro-status ${active?'on':''}">${active?'✓ Nitro is active':'Not subscribed'}</div><ul class="perk-list"><li>✨ Nitro badge on your profile</li><li>🎨 Premium profile styling</li><li>💜 Extra profile customization</li><li>🚀 Future Nitro perks</li></ul><button class="primary wide" onclick="toggleNitro()">${active?'Manage Nitro':'Get Ehood Nitro'}</button><div class="disabled-note">Payments are not connected yet, so this is a preview-only subscription.</div></div>`)}
function toggleNitro(){ui.nitro[me.id]=!ui.nitro[me.id];saveUI();closeModal();render();toast(ui.nitro[me.id]?'Nitro enabled ✨':'Nitro disabled')}
window.nitroInfo=nitroInfo;window.toggleNitro=toggleNitro;
async function profileModal(id=me.id){const u0=profiles.find(x=>x.id===id)||me,own=u0.id===me.id,nitro=nitroActive(u0),banner=ui.banners[u0.id];modal(`<div class="discord-profile-card"><div class="profile-banner ${banner?'has-custom':''}" style="${banner?`background-image:url('${banner}')`:''}"></div><div class="profile-head"><button class="pfpbutton ${own?'editable-pfp':''}" onclick="${own?'editProfile()':'void(0)'}"><span class="avatar-shell profile-avatar-shell"><img class="bigpfp" src="${pic(u0)}">${nitro?'<img class="nitro-pfp-badge profile-nitro-badge" src="ehood-nitro-badge.png" alt="Ehood Nitro">':''}</span>${own?'<span class="camera">📷</span>':''}</button><div class="profile-actions">${own?'<button class="secondary" onclick="editProfile()">Edit Profile</button>':'<button class="primary" onclick="closeModal();dm(\''+u0.id+'\')">Message</button>'}</div></div><div class="profile-info"><h2>${esc(u0.nickname||u0.username)} ${u0.verified?'<span class="verified">✓</span>':''} ${nitro?'<span class="nitro-badge">NITRO</span>':''}</h2><div class="profile-tag">@${esc(u0.username)}</div>${own?'<div class="owner-badge">EHOOD OWNER</div>':''}<div class="profile-section"><label>ABOUT ME</label><p>${esc(u0.bio||'Welcome to Ehood.')}</p></div><div class="profile-section"><label>MEMBER SINCE</label><p>Ehood member</p></div><div class="actions"><button class="secondary" onclick="closeModal()">Close</button>${own&&me.owner?'<button class="primary" onclick="ownerPanel()">👑 Owner Controls</button>':''}</div></div></div>`)}
async function editProfile(){const canBanner=!!me.owner||!!ui.nitro[me.id],banner=ui.banners[me.id]||'';modal(`<div class="edit-profile-discord"><div class="edit-title"><div><h2>Edit Profile</h2><p class="muted">Make your Ehood profile yours.</p></div><button class="close-x" onclick="closeModal()">×</button></div><div class="nitro-entry"><div class="nitro-entry-copy"><b>✨ Ehood Nitro</b><small>$2.99/month · unlock profile banners & premium customization</small></div><button class="primary" onclick="nitroInfo()">View Nitro</button></div><div class="edit-banner ${banner?'has-custom':''}" id="editBanner" style="${banner?`background-image:url('${banner}')`:''}"><div class="edit-pfp-wrap"><span class="avatar-shell edit-avatar-shell"><img id="editPreview" class="edit-pfp" src="${pic(me)}">${nitroActive(me)?'<img class="nitro-pfp-badge edit-nitro-badge" src="ehood-nitro-badge.png" alt="Ehood Nitro">':''}</span><button class="change-pfp" onclick="document.getElementById('newPfp').click()">Change Avatar</button></div>${canBanner?`<button class="change-banner" onclick="document.getElementById('newBanner').click()">🖼️ Change Banner</button>`:'<div class="banner-locked">🔒 Banner is an Ehood Nitro feature</div>'}</div><input id="newPfp" class="hidden-file" type="file" accept="image/*" onchange="previewPfp(event)"><input id="newBanner" class="hidden-file" type="file" accept="image/*" onchange="previewBanner(event)"><div class="field"><label>DISPLAY NAME</label><input id="newNick" value="${esc(me.nickname||'')}" maxlength="32" placeholder="Display name"></div><div class="field"><label>USERNAME</label><input id="newUser" value="${esc(me.username)}" maxlength="24"></div><div class="field"><label>ABOUT ME</label><textarea id="newBio" maxlength="190" placeholder="Tell people about you...">${esc(me.bio||'')}</textarea></div><div class="profile-preview-note">Your avatar appears across Ehood, including chats and member lists.</div><div class="actions"><button class="secondary" onclick="closeModal()">Cancel</button><button class="primary" onclick="saveProfile()">Save Changes</button></div></div>`)}
function previewPfp(e){const f=e.target.files[0];if(f)readFile(f).then(x=>$('#editPreview').src=x)}
function previewBanner(e){const f=e.target.files[0];if(f)readFile(f).then(x=>{const el=$('#editBanner');el.style.backgroundImage=`url('${x}')`;el.classList.add('has-custom');el.dataset.banner=x})}
window.previewBanner=previewBanner;
window.editProfile=editProfile;window.previewPfp=previewPfp;
async function saveProfile(){const name=$('#newUser').value.trim().replace(/^@/,'');if(!/^[a-zA-Z0-9_.-]{2,24}$/.test(name))return toast('Username must be 2–24 letters, numbers, _, ., or -.');let avatar=me.avatar;const f=$('#newPfp').files[0];if(f)avatar=await readFile(f);const nick=$('#newNick').value.trim(),bio=$('#newBio').value.trim();const bannerEl=$('#editBanner');const banner=bannerEl?.dataset?.banner||ui.banners[me.id]||'';if(banner&&!((me.owner)||ui.nitro[me.id]))return toast('Ehood Nitro is required for profile banners.');if(localMode){const a=getLocalAccounts(),taken=a.some(x=>x.id!==me.id&&x.username.toLowerCase()===name.toLowerCase());if(taken)return toast('Username already taken.');const i=a.findIndex(x=>x.id===me.id);a[i]={...a[i],username:name,nickname:nick,bio,avatar};saveLocalAccounts(a);me=a[i];if(banner)ui.banners[me.id]=banner;else delete ui.banners[me.id];saveUI();await refreshProfiles();closeModal();render();toast('Profile updated.');return}const {data,error}=await supa.from('profiles').update({username:name,nickname:nick,bio,avatar}).eq('id',me.id).select().single();if(error)return toast(error.code==='23505'?'Username already taken.':'Could not save profile.');me=data;await refreshProfiles();closeModal();render();toast('Profile updated.')}
window.saveProfile=saveProfile;
function settingsModal(){modal(`<div class="settings-page"><h2>Settings</h2><div class="settings-item" onclick="closeModal();editProfile()"><div><b>Profile</b><small>Avatar, display name, username and bio</small></div><span>›</span></div><div class="settings-item" onclick="closeModal();nitroInfo()"><div><b>Ehood Nitro</b><small>$2.99/month · premium profile features</small></div><span class="settings-nitro">✨</span></div>${me.owner?'<div class="settings-item" onclick="ownerPanel()"><div><b>Owner Controls</b><small>Verification, mute and ban controls</small></div><span>👑</span></div>':''}<div class="actions"><button class="secondary" onclick="closeModal()">Close</button></div></div>`)}
window.settingsModal=settingsModal;
async function ownerPanel(){if(!ownerGuard())return;await refreshProfiles();const rows=profiles.map(u=>{const va=u.verified?'unverify':'verify',ma=u.muted?'unmute':'mute',ba=u.banned?'unban':'ban';return `<div class="mod-row">${avatarHTML(u)}<div class="mod-user"><b>@${esc(u.username)} ${u.verified?'<span class="verified">✓</span>':''}</b><small>${u.id===me.id?'You · Owner':u.banned?'Banned':u.muted?'Muted':'Normal'}</small></div><div class="mod-actions">${u.id!==me.id?`<button class="tiny" onclick="moderateUser('${u.id}','${va}')">${u.verified?'Remove ✓':'Give ✓'}</button><button class="tiny" onclick="moderateUser('${u.id}','${ma}')">${u.muted?'Unmute':'Mute'}</button><button class="tiny danger" onclick="moderateUser('${u.id}','${ba}')">${u.banned?'Unban':'Ban'}</button>`:'<span class="owner-badge">OWNER</span>'}</div></div>`}).join('');modal(`<div class="owner-panel"><h2>👑 Ehood Owner</h2><p class="muted">Owner-only controls.</p><div class="mod-list">${rows||'<p class="muted">No users yet.</p>'}</div><div class="actions"><button class="secondary" onclick="closeModal()">Close</button></div></div>`)}
window.ownerPanel=ownerPanel;
async function moderateUser(id,action){if(!ownerGuard())return;if(localMode){const a=getLocalAccounts(),i=a.findIndex(x=>x.id===id);if(i<0)return;const map={verify:'verified',unverify:'verified',ban:'banned',unban:'banned',mute:'muted',unmute:'muted'};a[i][map[action]]=!['unverify','unban','unmute'].includes(action);saveLocalAccounts(a);if(id===me.id)me=a[i];await refreshProfiles();render();ownerPanel();toast('Done.');return}const rpc={verify:'owner_verify_user',unverify:'owner_unverify_user',ban:'owner_ban_user',unban:'owner_unban_user',mute:'owner_mute_user',unmute:'owner_unmute_user'}[action];const {error}=await supa.rpc(rpc,{target_id:id});if(error)return toast('Owner action failed.');await loadMe(me.id);await refreshProfiles();render();ownerPanel();toast('Done.')}
window.moderateUser=moderateUser;
function addCommunity(){modal(`<div class="create-group"><h2>Create a Group</h2><p class="muted">Start a private Ehood space with text and voice channels.</p><div class="group-icon-preview" id="groupIconPreview">G</div><div class="field"><label>GROUP NAME</label><input id="groupName" maxlength="28" placeholder="My group" oninput="updateGroupIcon()"></div><div class="field"><label>GROUP ICON</label><input id="groupIcon" maxlength="2" placeholder="G" oninput="updateGroupIcon()"></div><div class="actions"><button class="secondary" onclick="closeModal()">Cancel</button><button class="primary" onclick="createGroup()">Create Group</button></div></div>`)}
function updateGroupIcon(){const v=($('#groupIcon').value.trim()||$('#groupName').value.trim()[0]||'G').slice(0,2).toUpperCase();$('#groupIconPreview').textContent=v} window.updateGroupIcon=updateGroupIcon;
function createGroup(){const name=$('#groupName').value.trim();if(!name)return toast('Enter a group name.');const icon=($('#groupIcon').value.trim()||name[0]).slice(0,2).toUpperCase();const g={id:crypto.randomUUID(),name,icon,owner_id:me.id};ui.groups.push(g);saveUI();activeGroupId=g.id;current='general';closeModal();render();toast(`${name} created!`)}
window.addCommunity=addCommunity;window.createGroup=createGroup;
function joinVoice(groupId,name){const g=groupId==='ehood'?{name:'Ehood'}:groupById(groupId);modal(`<div class="voice-call"><div class="voice-orb">🔊</div><h2>${esc(g.name)} · ${esc(name)}</h2><p class="muted">Voice room</p><div class="call-status" id="callStatus">Ready to join</div><div class="call-controls"><button class="call-btn" id="micBtn" onclick="toggleMic()">🎙️</button><button class="call-btn hangup" onclick="leaveVoice()">☎</button></div><p class="disabled-note">Microphone access is available in the call UI. Multi-user voice requires a live signaling service to connect other devices.</p></div>`)}
function toggleMic(){const b=$('#micBtn');if(!b)return;b.classList.toggle('off');b.textContent=b.classList.contains('off')?'🔇':'🎙️';$('#callStatus').textContent=b.classList.contains('off')?'Microphone muted':'Microphone on'}
function leaveVoice(){closeModal();toast('Left voice room.')} window.joinVoice=joinVoice;window.toggleMic=toggleMic;window.leaveVoice=leaveVoice;
$('#profileBtn').onclick=()=>profileModal();$('#mobileProfileBtn').onclick=()=>profileModal();$('#settingsBtn').onclick=settingsModal;$('#logoutBtn').onclick=async()=>{if(localMode){localStorage.removeItem(localSessionKey);me=null;$('#mainView').classList.add('hidden');$('#authView').classList.remove('hidden')}else await supa.auth.signOut()};$('#addCommunity').onclick=addCommunity;$('#communitySettings').onclick=settingsModal;$('#nitroBtn').onclick=nitroInfo;$('#searchBtn').onclick=()=>toast('Search is coming soon.');$('#plus').onclick=()=>$('#imageInput').click();$('#membersBtn').onclick=()=>document.querySelector('.members')?.classList.toggle('hidden');
$('#authForm').onsubmit=async e=>{e.preventDefault();const mode=e.currentTarget.dataset.mode||'signin',email=$('#authEmail').value.trim().toLowerCase(),pass=$('#authPassword').value;if(mode==='signup'){const username=$('#authUsername').value.trim().replace(/^@/,'');if(!/^[a-zA-Z0-9_.-]{2,24}$/.test(username))return $('#authError').textContent='Username must be 2–24 letters, numbers, _, ., or -.';if(localMode){const a=getLocalAccounts();if(a.some(x=>x.username.toLowerCase()===username.toLowerCase()))return $('#authError').textContent='That username is already taken.';if(a.some(x=>x.email.toLowerCase()===email))return $('#authError').textContent='That email is already registered.';let avatar=null;const f=$('#authPfp').files[0];if(f)avatar=await readFile(f);const id=crypto.randomUUID(),first=!a.length,u={id,username,email,password:pass,avatar,bio:'',nickname:'',verified:first,owner:first,muted:false,banned:false};a.push(u);saveLocalAccounts(a);localStorage.setItem(localSessionKey,id);me=u;await refreshProfiles();openApp();return}const {data:available}=await supa.rpc('username_available',{candidate:username});if(available===false)return $('#authError').textContent='That username is already taken.';let avatar=null;const f=$('#authPfp').files[0];if(f)avatar=await readFile(f);const {data,error}=await supa.auth.signUp({email,password:pass,options:{data:{username,nickname:'',bio:'',avatar}}});if(error)return $('#authError').textContent=error.message;if(!data.session)return $('#authError').textContent='Account created. Check your email to verify it, then sign in.';await loadMe(data.user.id);openApp()}else{if(localMode){const u=getLocalAccounts().find(x=>x.email.toLowerCase()===email&&x.password===pass);if(!u)return $('#authError').textContent='Incorrect email or password.';if(u.banned)return $('#authError').textContent='This account is banned from Ehood.';localStorage.setItem(localSessionKey,u.id);me=u;await refreshProfiles();openApp();return}const {data,error}=await supa.auth.signInWithPassword({email,password:pass});if(error)return $('#authError').textContent=error.message;await loadMe(data.user.id);openApp()}};
boot();
