-- Ehood V5 database setup
-- 1) Create a Supabase project.
-- 2) Replace OWNER_EMAIL below with YOUR email, then run this whole file in Supabase SQL Editor.
-- 3) Put the project's URL and anon/publishable key into config.js.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  nickname text not null default '',
  bio text not null default '',
  avatar text,
  verified boolean not null default false,
  owner boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists profiles_username_lower_idx on public.profiles (lower(username));

alter table public.profiles enable row level security;

drop policy if exists "profiles are public" on public.profiles;
create policy "profiles are public" on public.profiles for select using (true);

drop policy if exists "users insert own profile" on public.profiles;
create policy "users insert own profile" on public.profiles for insert with check (auth.uid() = id);

drop policy if exists "users update own profile" on public.profiles;
create policy "users update own profile" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);

-- Prevent clients from assigning owner/verified status themselves.
create or replace function public.keep_verified_server_controlled()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    new.owner := (lower(coalesce((select email from auth.users where id = new.id),'')) = 'threatenn@outlook.com');
    new.verified := new.owner;
  elsif tg_op = 'UPDATE' then
    new.verified := old.verified;
    new.owner := old.owner;
  end if;
  return new;
end;
$$;

drop trigger if exists profiles_verified_guard on public.profiles;
create trigger profiles_verified_guard
before insert or update on public.profiles
for each row execute function public.keep_verified_server_controlled();

-- Replace this email with the Ehood owner's email BEFORE running.
create or replace function public.claim_ehood_owner()
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare owner_email text := 'threatenn@outlook.com';
begin
  if lower(coalesce(auth.jwt()->>'email','')) <> lower(owner_email) then
    return false;
  end if;
  update public.profiles set owner = true, verified = true where id = auth.uid();
  return found;
end;
$$;
revoke all on function public.claim_ehood_owner() from public;
grant execute on function public.claim_ehood_owner() to authenticated;

-- Signup trigger: create a blank profile automatically after Auth creates a user.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, username, nickname, bio, avatar, owner, verified)
  values (
    new.id,
    coalesce(nullif(new.raw_user_meta_data->>'username',''), 'user_' || substr(replace(new.id::text,'-',''),1,8)),
    coalesce(new.raw_user_meta_data->>'nickname',''),
    coalesce(new.raw_user_meta_data->>'bio',''),
    new.raw_user_meta_data->>'avatar',
    lower(coalesce(new.email,'')) = 'threatenn@outlook.com',
    lower(coalesce(new.email,'')) = 'threatenn@outlook.com'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- Helpful RPC for checking a username without exposing private Auth data.
create or replace function public.username_available(candidate text)
returns boolean
language sql
security invoker
set search_path = public
as $$
  select not exists (
    select 1 from public.profiles
    where lower(username) = lower(trim(both '@' from candidate))
  );
$$;
grant execute on function public.username_available(text) to anon, authenticated;



-- Shared Ehood chat. Run this after the main schema above.
create table if not exists public.ehood_messages (
  id bigint generated by default as identity primary key,
  channel_key text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  username text not null,
  avatar text,
  text text not null default '',
  image text,
  image_name text,
  created_at timestamptz not null default now(),
  edited boolean not null default false
);
create index if not exists ehood_messages_channel_created_idx on public.ehood_messages(channel_key,created_at);
alter table public.ehood_messages enable row level security;
drop policy if exists "chat read authenticated" on public.ehood_messages;
create policy "chat read authenticated" on public.ehood_messages for select to authenticated using (
  channel_key not like '%:dm_%' or channel_key like '%:dm_' || auth.uid()::text || '_%' or channel_key like '%:dm_%_' || auth.uid()::text
);
drop policy if exists "chat insert own" on public.ehood_messages;
create policy "chat insert own" on public.ehood_messages for insert to authenticated with check (auth.uid()=user_id);
drop policy if exists "chat update own" on public.ehood_messages;
create policy "chat update own" on public.ehood_messages for update to authenticated using (auth.uid()=user_id) with check (auth.uid()=user_id);
drop policy if exists "chat delete own" on public.ehood_messages;
create policy "chat delete own" on public.ehood_messages for delete to authenticated using (auth.uid()=user_id);
-- Enable Supabase Realtime for instant message updates.
do $$ begin
  alter publication supabase_realtime add table public.ehood_messages;
exception when duplicate_object then null;
end $$;

-- Discord-style Ehood servers/groups
create table if not exists public.ehood_groups (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  vanity text not null unique,
  icon_url text,
  banner_url text,
  created_at timestamptz not null default now()
);
create unique index if not exists ehood_groups_vanity_lower_idx on public.ehood_groups(lower(vanity));
alter table public.ehood_groups enable row level security;
drop policy if exists "groups are public" on public.ehood_groups;
create policy "groups are public" on public.ehood_groups for select using (true);
drop policy if exists "users create groups" on public.ehood_groups;
create policy "users create groups" on public.ehood_groups for insert to authenticated with check (auth.uid()=owner_id);
drop policy if exists "owners update groups" on public.ehood_groups;
create policy "owners update groups" on public.ehood_groups for update to authenticated using (auth.uid()=owner_id) with check (auth.uid()=owner_id);
drop policy if exists "owners delete groups" on public.ehood_groups;
create policy "owners delete groups" on public.ehood_groups for delete to authenticated using (auth.uid()=owner_id);

-- Ehood V28 permissions + persistent Nitro/verification/moderation + atomic server claims.
alter table public.profiles add column if not exists nitro boolean not null default false;
alter table public.profiles add column if not exists muted boolean not null default false;
alter table public.profiles add column if not exists banned boolean not null default false;

create or replace function public.keep_profile_server_controlled()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare owner_email text := 'threatenn@outlook.com';
begin
  if tg_op = 'INSERT' then
    new.owner := (lower(coalesce((select email from auth.users where id = new.id),'')) = lower(owner_email));
    new.verified := new.owner;
    new.nitro := new.owner;
    new.muted := false;
    new.banned := false;
  elsif tg_op = 'UPDATE' then
    new.owner := old.owner;
    if not (lower(coalesce((select email from auth.users where id = auth.uid()),'')) = lower(owner_email)) then
      new.verified := old.verified;
      new.nitro := old.nitro;
      new.muted := old.muted;
      new.banned := old.banned;
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists profiles_verified_guard on public.profiles;
drop trigger if exists profiles_control_guard on public.profiles;
create trigger profiles_control_guard
before insert or update on public.profiles
for each row execute function public.keep_profile_server_controlled();

create or replace function public.claim_ehood_owner()
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare owner_email text := 'threatenn@outlook.com';
begin
  if lower(coalesce(auth.jwt()->>'email','')) <> lower(owner_email) then return false; end if;
  update public.profiles set owner=true, verified=true, nitro=true where id=auth.uid();
  return found;
end;
$$;
revoke all on function public.claim_ehood_owner() from public;
grant execute on function public.claim_ehood_owner() to authenticated;

-- Only the owner can change another user's moderation, Nitro, or verified status.
create or replace function public.owner_ban_user(target_id uuid)
returns boolean language plpgsql security definer set search_path=public as $$
begin
  if lower(coalesce(auth.jwt()->>'email','')) <> 'threatenn@outlook.com' then return false; end if;
  update public.profiles set banned=true where id=target_id and owner=false;
  return found;
end; $$;
create or replace function public.owner_unban_user(target_id uuid)
returns boolean language plpgsql security definer set search_path=public as $$
begin
  if lower(coalesce(auth.jwt()->>'email','')) <> 'threatenn@outlook.com' then return false; end if;
  update public.profiles set banned=false where id=target_id;
  return found;
end; $$;
create or replace function public.owner_set_nitro(target_id uuid, enabled boolean)
returns boolean language plpgsql security definer set search_path=public as $$
begin
  if lower(coalesce(auth.jwt()->>'email','')) <> 'threatenn@outlook.com' then return false; end if;
  update public.profiles set nitro=enabled where id=target_id and (owner=false or enabled=true);
  return found;
end; $$;
create or replace function public.owner_set_verified(target_id uuid, enabled boolean)
returns boolean language plpgsql security definer set search_path=public as $$
begin
  if lower(coalesce(auth.jwt()->>'email','')) <> 'threatenn@outlook.com' then return false; end if;
  update public.profiles set verified=enabled where id=target_id and (owner=false or enabled=true);
  return found;
end; $$;
revoke all on function public.owner_ban_user(uuid) from public;
revoke all on function public.owner_unban_user(uuid) from public;
revoke all on function public.owner_set_nitro(uuid,boolean) from public;
revoke all on function public.owner_set_verified(uuid,boolean) from public;
grant execute on function public.owner_ban_user(uuid) to authenticated;
grant execute on function public.owner_unban_user(uuid) to authenticated;
grant execute on function public.owner_set_nitro(uuid,boolean) to authenticated;
grant execute on function public.owner_set_verified(uuid,boolean) to authenticated;

-- Server creation must be authorized in the database, not only hidden in the UI.
drop policy if exists "users create groups" on public.ehood_groups;
create policy "nitro or owner create groups" on public.ehood_groups
for insert to authenticated with check (
  auth.uid()=owner_id and exists (select 1 from public.profiles p where p.id=auth.uid() and (p.owner=true or p.nitro=true) and p.banned=false)
);

create or replace function public.create_ehood_group(p_name text,p_vanity text,p_icon_url text default null,p_banner_url text default null)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_vanity text := lower(trim(both '/' from trim(p_vanity))); g public.ehood_groups%rowtype;
begin
  if not exists(select 1 from public.profiles where id=auth.uid() and (owner=true or nitro=true) and banned=false) then
    return jsonb_build_object('ok',false,'reason','not_allowed');
  end if;
  if not v_vanity ~ '^[a-z0-9-]{2,24}$' then return jsonb_build_object('ok',false,'reason','invalid_vanity'); end if;
  if exists(select 1 from public.ehood_groups where lower(vanity)=v_vanity) then return jsonb_build_object('ok',false,'reason','vanity_claimed'); end if;
  begin
    insert into public.ehood_groups(owner_id,name,vanity,icon_url,banner_url) values(auth.uid(),trim(p_name),v_vanity,p_icon_url,p_banner_url) returning * into g;
  exception when unique_violation then
    if exists(select 1 from public.ehood_groups where lower(vanity)=v_vanity) then return jsonb_build_object('ok',false,'reason','vanity_claimed'); end if;
    raise;
  end;
  return jsonb_build_object('ok',true,'group',to_jsonb(g));
end; $$;
revoke all on function public.create_ehood_group(text,text,text,text) from public;
grant execute on function public.create_ehood_group(text,text,text,text) to authenticated;

create or replace function public.update_ehood_group(p_group_id uuid,p_name text,p_vanity text,p_icon_url text default null,p_banner_url text default null)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_vanity text := lower(trim(both '/' from trim(p_vanity))); g public.ehood_groups%rowtype;
begin
  if not exists(select 1 from public.ehood_groups where id=p_group_id and owner_id=auth.uid()) then return jsonb_build_object('ok',false,'reason','not_owner'); end if;
  if not v_vanity ~ '^[a-z0-9-]{2,24}$' then return jsonb_build_object('ok',false,'reason','invalid_vanity'); end if;
  if exists(select 1 from public.ehood_groups where lower(vanity)=v_vanity and id<>p_group_id) then return jsonb_build_object('ok',false,'reason','vanity_claimed'); end if;
  begin
    update public.ehood_groups set name=trim(p_name),vanity=v_vanity,icon_url=p_icon_url,banner_url=p_banner_url where id=p_group_id and owner_id=auth.uid() returning * into g;
  exception when unique_violation then
    if exists(select 1 from public.ehood_groups where lower(vanity)=v_vanity and id<>p_group_id) then return jsonb_build_object('ok',false,'reason','vanity_claimed'); end if;
    raise;
  end;
  return jsonb_build_object('ok',true,'group',to_jsonb(g));
end; $$;
revoke all on function public.update_ehood_group(uuid,text,text,text,text) from public;
grant execute on function public.update_ehood_group(uuid,text,text,text,text) to authenticated;
